server:
  port: 9100

spring:
  application:
    name: shop-web
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.112.128:8848
  thymeleaf:
    mode: LEGACYHTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 30000
        connectTimeout: 10000
  hystrix:
    enabled: false #防止自定义feign接口无法接收对象
# 设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

thread:
  pool:
    core_pool_size: 16
    maximum_pool_size: 32
    keep_alive_time: 30
    work_queue_num: 100