server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: shop-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.112.128:8848
  rabbitmq:
    host: 192.168.112.128
    port: 5672
    username: admin
    password: 123
  redis:
    host: 192.168.112.128
    port: 6389
    database: 0
    timeout: 1800000
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.112.128:3306/shop_product?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  shardingsphere:
    datasource:
      names: write-node,read-node1,read-node2
      write-node:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3306/shop_product_01?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      read-node1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3306/shop_product_02?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      read-node2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3306/shop_product_03?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    rules:
      readwrite-splitting:
        data-sources:
          master-node:
            type: static
            props:
              write-data-source-name: write-node
              read-data-source-names: read-node1,read-node2
            load-balancer-name: read-lb
        load-balancers:
          read-lb:
            type: ROUND_ROBIN

#自定义配置类
minio:
  endpoint: http://192.168.112.128:9000
  accessKey: enjoy6288
  secretKey: enjoy6288
  bucketName: godhand